name: CI

on: 

push: 

branches: 

- main

jobs:

__BLANK 2__:

    runs-on: ubuntu-latest

    name: Run ESLint + Jest

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint

    - run: npm run test
